name: Update EPG

on:
  push:
    paths:
      - "channels.json"     # only run when this file changes
  schedule:
    - cron: "0 3 * * *"     # daily at 3 AM UTC
  workflow_dispatch:         # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # allow committing back to repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run merge script
        run: python merge_epg.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add epg.xml
          git commit -m "Auto-update EPG" || echo "No changes"
          git push

      - name: Trigger Netlify Build
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
