name: Update EPG

on:
  push:
    paths:
      - "channels.json"
      - "merge_epg.py"
  schedule:
    - cron: "0 0 * * *"   # Run daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run merge script
        run: python merge_epg.py

      - name: Commit and push if epg.xml changed
        run: |
          git config user.name "epg-bot"
          git config user.email "epg-bot@users.noreply.github.com"
          git add epg.xml
          git diff --cached --quiet || git commit -m "Update epg.xml"
          git push

      - name: Trigger Netlify Build
        if: success()
        run: |
          curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }}
